apiVersion: v1
kind: Pod 
metadata:
  name: using-ceph
spec:
  containers:
  - image: busybox
    name: using-ceph
    volumeMounts:
    - name: ceph-volume
      mountPath: /test-ceph
  volumes:
  - name: ceph-volume
    cephfs:
      path: /some/path/in/side/cephfs
      monitors: "10.16.154.78:6789"
      secretFile: "/etc/ceph/admin.secret"