apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: mycronjob
spec:
    schedule: "*/1 * * * *"
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                    - name: hello
                      image: busybox
                      command: ["echo", "hello k8s cronjob"]
                    restartPolicy: OnFailure